{
 "title": "DocSpace dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_receiving,http_req_sending,http_req_waiting"
   },
   {
    "name": "Scenarios",
    "query": "const_vus_scenario, shared_iter_scenario, per_vu_scenario, const_arrival_rate_scenario, ramp_arrival_rate_scenario, ext_controlled_scenario"
   }
  ]
 },
 "panels": [
  { "title": "All data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests by URL (by name)",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "scenario::tag" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95), count(\"value\") FROM /^$Measurement$/ WHERE $timeFilter GROUP BY \"name\"::tag, \"scenario\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests by URL (All)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "method::tag" ], "type": "tag" },
      { "params": [ "scenario::tag" ], "type": "tag" },
      { "params": [ "status::tag" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95), count(\"value\") FROM /^$Measurement$/ WHERE $timeFilter GROUP BY \"name\"::tag, \"method\"::tag, \"scenario\"::tag, \"status\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checks (all)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "check::tag" ], "type": "tag" },
      { "params": [ "scenario::tag" ], "type": "tag" }
     ],
     "measurement": "checks",
     "query": "SELECT sum(\"value\"), count(\"value\") FROM \"checks\" WHERE $timeFilter GROUP BY \"check\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Iteration duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "iteration_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Comparison of sccenarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Scenario data",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "scenario_duration::tag" ], "type": "tag" },
      { "params": [ "scenario_exec::tag" ], "type": "tag" },
      { "params": [ "scenario_executor::tag" ], "type": "tag" },
      { "params": [ "scenario_gracefulStop::tag" ], "type": "tag" },
      { "params": [ "scenario_startTime::tag" ], "type": "tag" },
      { "params": [ "scenario_vus::tag" ], "type": "tag" },
      { "params": [ "scenario_gracefulRampDown::tag" ], "type": "tag" },
      { "params": [ "scenario_iterations::tag" ], "type": "tag" },
      { "params": [ "scenario_maxDuration::tag" ], "type": "tag" },
      { "params": [ "scenario_maxVUs::tag" ], "type": "tag" },
      { "params": [ "scenario_preAllocatedVUs::tag" ], "type": "tag" },
      { "params": [ "scenario_rate::tag" ], "type": "tag" },
      { "params": [ "scenario_stages::tag" ], "type": "tag" },
      { "params": [ "scenario_startRate::tag" ], "type": "tag" },
      { "params": [ "scenario_startVUs::tag" ], "type": "tag" },
      { "params": [ "scenario_timeUnit::tag" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT count(\"value\") FROM /^$Measurement$/ WHERE $timeFilter, fill(null) GROUP BY \"scenario_duration\"::tag, \"scenario_exec\"::tag, \"scenario_executor\"::tag, \"scenario_gracefulStop\"::tag, \"scenario_startTime\"::tag, \"scenario_vus\"::tag fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scenarios",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group::tag" ], "type": "tag" },
      { "params": [ "method::tag" ], "type": "tag" },
      { "params": [ "scenario::tag" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT max(\"value\"), min(\"value\"), mean(\"value\"), median(\"value\") FROM /^$Measurement$/ WHERE $timeFilter GROUP BY time(10m), \"group\"::tag, \"method\"::tag, \"scenario\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (mean time, method POST)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (mean time, method PUT)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (mean time, method GET)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (mean time, method DELETE)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (max time, method POST)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (max time, method PUT)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (max time, method GET)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (max time, method DELETE)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (min time, method POST)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (min time, method PUT)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (min time, method GET)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (min time, method DELETE)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (median time, method POST)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "POST" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (median time, method PUT)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "PUT" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (median time, method GET)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Comparison of scenarios (median time, method DELETE)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "const_vus_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "per_vu_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "shared_iter_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "const_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ramp_arrival_rate_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    },
    {
     "measurement": "ext_controlled_scenario",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "method::tag", "operator": "=", "value": "DELETE" }
     ]
    }
   ]
  },
  { "title": "$Scenarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }, "repeat": "Scenarios" },
  {
   "title": "$Scenarios (count)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Scenarios (max)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Scenarios (min)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Scenarios (mean)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Scenarios (median)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Scenarios (p95)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Scenarios (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "query": "SELECT max(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "query": "SELECT percentile(\"value\", 90) FROM /^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Scenarios$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Scenarios (over time)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "query": "SELECT \"value\" FROM $Scenarios WHERE $timeFilter and value > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" }
     ]
    }
   ]
  },
  {
   "title": "Checks (all)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 96 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "check::tag" ], "type": "tag" }
     ],
     "measurement": "checks",
     "query": "SELECT sum(\"value\"),  count(\"value\") FROM \"checks\" WHERE (\"scenario\"::tag = 'const_vus_scenario') AND $timeFilter GROUP BY \"check\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "scenario::tag", "operator": "=~", "value": "/^$Scenarios$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scenario::tag", "operator": "=~", "value": "/^$Scenarios$/" }
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 96 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scenario::tag", "operator": "=~", "value": "/^$Scenarios$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "repeat": "Measurement",
   "collapsed": true,
   "panels": [
    {
     "title": "$Measurement (count)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$Measurement (max)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$Measurement (min)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$Measurement (mean)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$Measurement (median)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$Measurement (p95)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT max(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT percentile(\"value\", 90) FROM /^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$Measurement$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$Measurement (over time)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "measurement": "/^$Measurement$/",
       "query": "SELECT \"value\" FROM $Measurement WHERE $timeFilter and value > 0",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$URL$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}